apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v1
  namespace: cpu
  labels:
    app: api
    version: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      version: "1"
  template:
    metadata:
      labels:
        app: api
        version: "1"
      annotations:
    spec:
      containers:
        - name: api
          image: nginx
          ports:
          - containerPort: 80
            name: http
          volumeMounts:
          - mountPath: /usr/share/nginx/html/
            name: api
          - mountPath: /usr/share/nginx/html/api/
            name: api-api
          - mountPath: /etc/nginx/conf.d
            readOnly: true
            name: nginx-conf
      initContainers:
        - name: api-init
          image: everpeace/curl-jq
          volumeMounts:
          - mountPath: /usr/share/nginx/html/
            name: api
          - mountPath: /usr/share/nginx/html/api/
            name: api-api
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - "sh"
            - "-c"
            - | 
              cat <<EOF >/usr/share/nginx/html/index.html
              
              Service-Name     = api
              Service-Version  = v1
              Service-ID       = ${POD_NAME}
              Pod IP address   = ${POD_IP}
              Node             = ${HOST_NAME}
              
              EOF
              cat <<EOF >/usr/share/nginx/html/api/index.html
              
              Service-Name     = api
              Service-Version  = v1
              Service-ID       = ${POD_NAME}
              Pod IP address   = ${POD_IP}
              Node             = ${HOST_NAME}
              
              EOF
      # serviceAccountName: api
      volumes:
        - name: api
          emptyDir: {}
        - name: api-api
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: default.conf
                path: default.conf

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: api

---         
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: cpu
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: api-v1
  namespace: cpu
  labels:
    app: api
    version: "1"
spec:
  selector:
    app: api
    version: "1"
  ports:
    - name: api
      port: 80
      targetPort: 80
